# Generated by Django 4.2.1 on 2023-05-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Sem descrição disponível'),
        ),
    ]
