# Generated by Django 4.2.1 on 2023-05-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_user_created_at_booktransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookTransaction',
            new_name='Transaction',
        ),
    ]
