# Generated by Django 4.2.1 on 2023-05-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_rename_created_at_book_createsd_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='createsd_at',
            new_name='created_at',
        ),
    ]
