# Generated by Django 4.2.1 on 2023-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0020_transaction_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book_title',
            field=models.CharField(default='Sem título', max_length=200),
        ),
    ]
