# Generated by Django 4.2.1 on 2023-05-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0022_alter_transaction_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='active',
        ),
    ]
