# Generated by Django 4.2.1 on 2023-05-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0025_alter_transaction_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
